feat(status-api): main app setup
DeFiCh/jellyfish pull request #1275
Opened 2022-03-28 12:29 UTC by joeldavidw

#### What this PR does / why we need it:

#### Which issue(s) does this PR fixes?:

Part of #1270 

#### Additional comments?:

2022-03-29 07:08 UTC, fuxingloh requested changes
@nichellekoh I recommend you create another PR with the above suggested change

2022-03-29 07:08 UTC, fuxingloh commented on apps/status-api/README.md
> +## `/apps/ocean-api`
@nichellekoh need you update this.

2022-03-29 07:08 UTC, fuxingloh commented on apps/status-api/testing/StatusApiTesting.ts
> + * LegacyApi Testing framework.
```suggestion
 * StatusApi Testing framework.
```

2022-03-29 07:08 UTC, fuxingloh commented on apps/status-api/src/providers/WhaleApiClientProvider.ts
> +  private readonly clientCacheByNetwork: Map<SupportedNetwork, WhaleApiClient> = new Map()
We should follow `ocean-api`, `whale` structure where there is only one NETWORK type per server/instance.

2022-03-29 07:08 UTC, fuxingloh commented on apps/status-api/src/providers/WhaleApiClientProvider.ts
> +  private readonly clientCacheByNetwork: Map<SupportedNetwork, WhaleApiClient> = new Map()
So we can let the Load Balancer do the routing via, e.g. `/v0/mainnet` and `/v0/testnet`

2022-03-29 07:08 UTC, fuxingloh commented on apps/status-api/src/pipes/NetworkValidationPipe.ts
> +export class NetworkValidationPipe implements PipeTransform {
We don't need this, if we move to that structure.

2022-03-29 07:08 UTC, fuxingloh commented on apps/status-api/src/modules/WhaleApiModule.ts
> +export class WhaleApiProbeIndicator extends ProbeIndicator {
We can also move the use the default RPC probe if we move to the other structure.

2022-03-29 07:08 UTC, fuxingloh commented on apps/status-api/src/index.ts
> +export class RootServer {
Use RootServer abstraction that was just merged.

2022-03-30 02:31 UTC, nichellekoh commented
> @nichellekoh I recommend you create another PR with the above suggested change

@fuxingloh A separate PR has been created with the changes https://github.com/DeFiCh/jellyfish/pull/1292

2022-03-31 09:11 UTC, closed without merging