Add OP_RIPEMD160 opcode
DeFiCh/jellyfish pull request #203
Opened 2021-05-10 16:39 UTC by jingyi2811

/kind feature

Add OP_RIPEMD160 opcode

2021-05-10 18:24 UTC, fuxingloh requested changes
> I do not add any unit test to index.test.ts
> 
> The reason is I believe the unit test which was written for OP_HASH160 has included the testing of OP_RIPEMD160 as OP_HASH160 =The input is hashed twice: first with SHA-256 and then with RIPEMD-160.
> 
> Kindly advise if my decision was wrong

You need `index.test.ts` as they are different features. 
These are instructions for stack scripting, there are no magic to this. It's passed to defid to process. JS doesn't do anything with it. It merely parses it for client side rendering.

2021-05-11 08:05 UTC, jingyi2811 commented
Last commit message is wrong. It should be Add OP_RIPEMD160 unit test.

Not too sure if adding this unit test is enough to close this PR. Kindly advise if you think this is insufficient.

2021-05-11 08:06 UTC, fuxingloh approved these changes

2021-05-11 10:52 UTC, fuxingloh commented
@jingyi2811 to fix conflicting files

2021-05-12 03:59 UTC, canonbrother submitted a review, later dismissed

2021-05-12 04:04 UTC, fuxingloh requested changes

2021-05-12 04:04 UTC, fuxingloh commented on packages/jellyfish-transaction/__tests__/script/mapping.test.ts
> +import { OP_CODES, OP_RIPEMD160 } from '../../src/script'
I didn't catch this previously. do this instead:

```ts
import * as script from '../../src/script'
```

2021-05-12 04:06 UTC, fuxingloh commented on packages/jellyfish-network/__tests__/index.test.ts
> +import { getNetwork, MainNet, Network, RegTest, TestNet } from '../src'
revert this

2021-05-12 05:10 UTC, fuxingloh approved these changes

2021-05-12 05:10 UTC, merged