Add getDifficulty rpc
DeFiCh/jellyfish pull request #285
Opened 2021-05-24 13:54 UTC by izzycsy

Add getDifficulty

#### What kind of PR is this?:

/kind feature
Add getDifficulty rpc

2021-05-24 14:09 UTC, fuxingloh requested changes

2021-05-24 14:09 UTC, fuxingloh commented on website/docs/jellyfish/api/blockchain.md
> +
Keep in mind of code line breaks

```suggestion

## getDifficulty

Return the proof-of-work difficulty as a multiple of the minimum difficulty.

```ts tile="client.blockchain.getDifficulty()"
interface blockchain {
    getDifficulty (): Promise<number>
}
```
```

2021-05-24 14:09 UTC, fuxingloh commented on packages/jellyfish-api-core/src/category/blockchain.ts
> +   */
```suggestion
  /**
   * Get difficulty of chain.
   *
   * @return {Promise<number>}
   */
```

2021-05-24 14:09 UTC, fuxingloh commented on packages/jellyfish-api-core/src/category/blockchain.ts
> +   */
JSDocs need to be structured properly

2021-05-24 14:09 UTC, fuxingloh commented on packages/jellyfish-api-core/__tests__/category/blockchain.test.ts
> +
Remove this entire code section, it's not required. it's done by the parent `describe`.

2021-05-24 14:09 UTC, fuxingloh commented on packages/jellyfish-api-core/__tests__/category/blockchain.test.ts
> +      expect(getdifficulty).toBeGreaterThanOrEqual(0)
```suggestion
      const difficulty = await client.blockchain.getDifficulty()
      expect(difficulty).toBeGreaterThanOrEqual(0)
```

2021-05-24 14:09 UTC, fuxingloh commented on packages/jellyfish-api-core/__tests__/category/blockchain.test.ts
> +  // getDifficulty of masternode & non masternode
remove this line

2021-05-24 14:18 UTC, fuxingloh commented on packages/jellyfish-api-core/src/category/blockchain.ts
> +   * Get difficulty of chain.
This should be 
```
Get the proof-of-work difficulty as a multiple of the minimum difficulty.
```

2021-05-24 14:53 UTC, fuxingloh approved these changes

2021-05-25 01:56 UTC, thedoublejay approved these changes

2021-05-25 01:56 UTC, merged