Refactor all test for account be independent
DeFiCh/jellyfish pull request #301
Opened 2021-05-27 07:49 UTC by jingyi2811

#### What kind of PR is this?:

/kind

#### What this PR does / why we need it:
It’s getting very difficult to maintain side-effect and writing independent tests. Writing a clean and independent test is not easy, it requires a certain mastery with strong testing principles. Refactoring __tests__ in jellyfish-api-core will allow us to have a cleaner testing culture.

#### Which issue(s) does this PR fixes?:

Fixes #295

#### Additional comments?:

2021-05-27 07:59 UTC, jingyi2811 commented on packages/jellyfish-api-core/__tests__/category/account/getAccount.test.ts
> +    // [ '187.00000000@DBTC', '154.00000000@DETH' ]
Ya, the comment needed to be tailored accordingly. Will do so.

2021-05-27 08:28 UTC, fuxingloh requested changes

2021-05-27 08:28 UTC, fuxingloh commented on packages/jellyfish-api-core/__tests__/category/account/getAccount.test.ts
> +describe('masternode', () => {
for tests that only setup one container you can remove the describe block

2021-05-27 08:32 UTC, fuxingloh requested changes

2021-05-27 08:32 UTC, fuxingloh commented on packages/jellyfish-api-core/__tests__/category/account/getAccount.test.ts
> +describe('masternode', () => {
instead of calling it masternode, probably best to describe the setup e.g.

```suggestion
describe('Account with DBTC', () => {
```

2021-06-01 11:00 UTC, jingyi2811 commented
Suraj will be the owner of this PR

2021-06-02 00:59 UTC, fuxingloh approved these changes

2021-06-02 03:03 UTC, canonbrother approved these changes

2021-06-02 03:03 UTC, merged