`wallet.dumpPrivKey` and `wallet.importPrivKey` RPC
DeFiCh/jellyfish pull request #306
Opened 2021-05-27 14:13 UTC by siradji

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:
RPC wallet implementation #48 
#### Which issue(s) does this PR fixes?:

Fixes #

#### Additional comments?:

2021-05-28 08:11 UTC, fuxingloh requested changes

2021-05-28 08:11 UTC, fuxingloh commented on website/docs/jellyfish/api/wallet.md
> +Reveals the private key corresponding to 'address'. Then the importprivkey can be used with this output.
```suggestion
Reveals the private key corresponding to an address.
```

2021-05-28 08:11 UTC, fuxingloh commented on packages/jellyfish-api-core/src/category/wallet.ts
> +   * Then the importprivkey can be used with this output.
```suggestion
  /**
   * Reveals the private key corresponding to an address.
   *
```

2021-05-28 08:27 UTC, canonbrother reviewed
overall looks good.. but we have a new test structure.. gonna refactor a bit

2021-05-28 12:42 UTC, siradji commented
> overall looks good.. but we have a new test structure.. gonna refactor a bit

@canonbrother, i have implemented that.

2021-05-28 12:44 UTC, siradji commented on packages/jellyfish-api-core/__tests__/category/wallet.test.ts
> +    afterAll(async () => {
@fuxingloh , That's is done.

2021-05-28 17:57 UTC, fuxingloh submitted a review, later dismissed

2021-05-29 07:10 UTC, jingyi2811 commented on packages/jellyfish-api-core/__tests__/category/wallet/importPrivkey.test.ts
> +  it('should should import private key without failing ', async () => {
Extra should

2021-05-29 07:14 UTC, jingyi2811 commented on website/docs/jellyfish/api/wallet.md
> +  dumpPrivKey(address: string): Promise<string>
Add a space between dumpPrivKey and (address: string): Promise<string>

2021-05-29 07:15 UTC, jingyi2811 commented on website/docs/jellyfish/api/wallet.md
> +  importPrivKey(privkey: string, label: string = "", rescan: boolean = true): Promise<void>
Same

2021-05-30 02:57 UTC, jingyi2811 approved these changes

2021-05-30 07:42 UTC, fuxingloh approved these changes

2021-05-30 07:42 UTC, merged