Fix fail test in getChainTips RPC
DeFiCh/jellyfish pull request #327
Opened 2021-06-01 11:49 UTC by jingyi2811

#### What kind of PR is this?:

/kind fix

#### What this PR does / why we need it:
Fix fail test in getChainTips RPC which happens ocassionaly.

#### Which issue(s) does this PR fixes?:

Fixes #326

#### Additional comments?:

2021-06-01 13:40 UTC, jingyi2811 commented
The test passed in the local environment.
However, it fails in GitHub occasionally.
To ensure the new code is working, I rerun the test four times and all passed.

2021-06-01 15:12 UTC, jingyi2811 commented
I merge this branch to https://github.com/DeFiCh/jellyfish/pull/323 (The branch that Suraj faced this failed test)
and run the test 4 times. All passed.

2021-06-02 00:52 UTC, fuxingloh requested changes

2021-06-02 00:52 UTC, fuxingloh commented on packages/jellyfish-api-core/__tests__/category/blockchain/getChainTips.test.ts
> +    await container.waitForWalletCoinbaseMaturity()
```suggestion
    await container.waitForBlock(1)
```

This will make the test run faster.

2021-06-02 03:42 UTC, fuxingloh approved these changes

2021-06-02 03:50 UTC, merged