Add updateoracle rpc
DeFiCh/jellyfish pull request #341
Opened 2021-06-03 10:08 UTC by jingyi2811

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:

Add updateoracle rpc

#### Which issue(s) does this PR fixes?:

Fixes part of #202 

#### Additional comments?:

2021-06-05 14:49 UTC, fuxingloh requested changes
some clarification about txn id, txn id is also used for identifying oracle data.

This allows us to identify masternode as well, that's how you masternode id get generated.

2021-06-05 14:49 UTC, fuxingloh commented on packages/jellyfish-api-core/src/category/oracle.ts
> +   * @return {Promise<string>} txn id for txn created to appoint oracle
```suggestion
   * @return {Promise<string>} oracleid, also the txn id for txn created to appoint oracle
```

2021-06-06 10:46 UTC, fuxingloh approved these changes

2021-06-07 02:08 UTC, canonbrother approved these changes

2021-06-07 02:08 UTC, merged