Added `poolSwap` and `testPoolSwap` RPC
DeFiCh/jellyfish pull request #350
Opened 2021-06-07 11:23 UTC by siradji

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:

RPC implementation

#### Which issue(s) does this PR fixes?:

Fixes #48 

#### Additional comments?:

2021-06-07 12:10 UTC, jingyi2811 commented on website/docs/jellyfish/api/poolpair.md
> +export type PoolSwapResultType = `${number}&${string}`
Remove export

2021-06-07 12:13 UTC, jingyi2811 commented on packages/jellyfish-api-core/__tests__/category/poolpair/testPoolSwap.test.ts
> +  let address: string
Move this line to line 29

2021-06-07 12:25 UTC, jingyi2811 commented on website/docs/jellyfish/api/poolpair.md
> +interface PoolSwapInputs {
PoolSwapInputs is a decent name. But for this variable, we declare like below in other typescript file

```
export interface UTXO {
  txid: string
  vout: number
}
```

2021-06-07 12:26 UTC, jingyi2811 commented on packages/jellyfish-api-core/src/category/poolpair.ts
> +export interface PoolSwapInputs {
PoolSwapInputs is a decent name. But for this variable, we write this in other typescript file

```
export interface UTXO {
  txid: string
  vout: number
}
```

2021-06-07 13:22 UTC, jingyi2811 commented on packages/jellyfish-api-core/__tests__/category/poolpair/poolSwap.test.ts
> +    const poolswapHex = await client.poolpair.poolSwap(metadata)
Usually, we do not share 2 RPC in the same file.

2021-06-07 13:24 UTC, jingyi2811 commented
Thanks for asking me to review. @canonbrother has more experience in poopair. I guess it is related to poolswap / testpoolswap. He probably could help you better

2021-06-08 07:36 UTC, siradji commented
@canonbrother , i need you help in reviewing this PR. I'd want you to give me your opinion on the testing. I have a feeling there are more ways to implement more stringent testing. And also, is there a way to test a `poolswap` transaction without using the `testPoolSwap` RPC (refer to the picture below)

<img width="680" alt="image" src="https://user-images.githubusercontent.com/57817584/121143081-8e870500-c834-11eb-9898-52b4c2cf6dd8.png">

2021-06-08 07:40 UTC, monstrobishi requested changes

2021-06-08 07:40 UTC, monstrobishi commented on packages/jellyfish-api-core/__tests__/category/poolpair/poolSwap.test.ts
> +  it('should throw an error when invalid token is specified', async () => {
I would add another test that checks the max price protection. Do this by:

- Fund UTXOs for 2 different addresses
- Sending a tx with max price using first address
- Don't generate a block yet
- Send a second swap tx a big one using second addresss
- Then generate
- Confirm that swap wasn't performed due to max price protection

2021-06-09 04:25 UTC, canonbrother commented
1. test poolswap
  - expect reserveA, reserveB value (refer the calculation below)
  - check before after token balance
2. test poolswap with maxPrice

Calculation for your ref
```
10: 200 = sqrt(10*200) = 44.721359
from: DDAI, fromAmt: 6
? : 206 = sqrt(? * 206) = 44.72135955
? = 44.72135955^2 / 206 = 9.708755427
bal:  [ '90.29126214@0', '1794.00000000@1', '44.72134954@2' ]

from: DFI, fromAmt: 6
16 : ? = sqrt(16 * ?) = 44.72135955
? = 44.72135955^2 / 16 = 125.000225
bal:  [ '84.00000000@0', '1875.00000000@1', '44.72134954@2'
```
3. test poolswap against maxPrice
4. test poolswap against non-existence token
5. test poolswap against poolpair status false

2021-06-09 12:41 UTC, siradji commented
> 1. test poolswap (test respectively from diff coin swap)
> 
>   - expect reserveA, reserveB value (refer the calculation below)
> 
>   - check before after token balance
> 
> 2. test poolswap with maxPrice (don't need assert too details as **test poolswap ady done above**, just ensure it should be passed
> 
> 
> 
> Calculation for your reference
> 
> `note: the calculation is based on your poolpair "tokenA: 10, tokenB: 200" set up`
> 
> ```
> 
> beforeBal:  [ '90.00000000@0', '1800.00000000@1', '44.72134954@2' ]
> 
> 10: 200 = sqrt(10*200) = 44.721359
> 
> 
> 
> from: DDAI, fromAmt: 6
> 
> ? : 206 = sqrt(? * 206) = 44.72135955
> 
> ? = 44.72135955^2 / 206 = 9.708755427
> 
> afterBal:  [ '90.29126214@0', '1794.00000000@1', '44.72134954@2' ]
> 
> 
> 
> from: DFI, fromAmt: 6
> 
> 16 : ? = sqrt(16 * ?) = 44.72135955
> 
> ? = 44.72135955^2 / 16 = 125.000225
> 
> afterBal:  [ '84.00000000@0', '1875.00000000@1', '44.72134954@2'
> 
> ```
> 
> 3. test poolswap against maxPrice
> 
> 4. test poolswap against non-existence token
> 
> 5. test poolswap against poolpair status false
> 
> 
> 
>     

@canonbrother , the calculation is a little bit complex. I would appreciate it if you can clarify further.

2021-06-23 13:23 UTC, closed without merging