Added getunconfirmedbalance RPC
DeFiCh/jellyfish pull request #354
Opened 2021-06-08 07:05 UTC by aikchun

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:
Added getUnconfirmedBalance RPC
1. wallet.getUnconfirmedBalance

#### Which issue(s) does this PR fixes?:

Fixes `getunconfirmedbalance` #48

2021-06-17 09:02 UTC, canonbrother submitted a review, later dismissed

2021-06-17 09:50 UTC, jingyi2811 commented on packages/jellyfish-api-core/__tests__/category/wallet/getUnconfirmedBalance.test.ts
> +import { BigNumber } from '../../../src'
Use this `import BigNumber from 'bignumber.js'`
If you see `import { BigNumber } from '../../../src'` somewhere, they need to be refactored one day

2021-06-17 09:51 UTC, jingyi2811 commented on website/docs/jellyfish/api/wallet.md
> +  getUnconfirmedBalance(withTokens = false): Promise<number>
`getUnconfirmedBalance (withTokens: boolean = false): Promise<BigNumber>`

2021-06-17 09:54 UTC, jingyi2811 commented on packages/jellyfish-api-core/src/category/wallet.ts
> +   * @param {boolean} withTokens
@param {boolean} [withTokens=false]
This is an optional value
See https://jsdoc.app/tags-param.html#optional-parameters-and-default-values

2021-06-18 07:54 UTC, jingyi2811 approved these changes

2021-06-21 03:58 UTC, fuxingloh requested changes

2021-06-21 03:58 UTC, fuxingloh commented on packages/jellyfish-api-core/src/category/wallet.ts
> +    return await this.client.call('getunconfirmedbalance', [withTokens], 'bignumber')
```suggestion
    return await this.client.call('getunconfirmedbalance', [false], 'bignumber')
```

2021-06-21 06:10 UTC, aikchun commented on packages/jellyfish-api-core/src/category/wallet.ts
> +    return await this.client.call('getunconfirmedbalance', [withTokens], 'bignumber')
Removed the parameter and updated docs.

2021-06-21 07:52 UTC, jingyi2811 approved these changes

2021-06-21 08:14 UTC, merged