Added expansion and invalid OP_CODES
DeFiCh/jellyfish pull request #440
Opened 2021-07-05 14:06 UTC by Jouzo

#### What kind of PR is this?:
/kind feature

#### What this PR does / why we need it:

Adds expansion and invalid opcodes mentioned in #107 

#### Which issue(s) does this PR fixes?:

Fixes missing opcodes in #107 

#### Additional comments?:

2021-07-05 15:32 UTC, jingyi2811 commented
Nice!

2021-07-05 15:32 UTC, jingyi2811 submitted a review, later dismissed

2021-07-05 16:03 UTC, fuxingloh requested changes
minor whitespace to remove

2021-07-05 16:29 UTC, Jouzo commented
Where about ? It is not caught be the linter

2021-07-05 17:16 UTC, fuxingloh requested changes
my bad, I didn't attach it within my review

2021-07-05 17:16 UTC, fuxingloh commented on packages/jellyfish-transaction/src/script/expansion.ts
> +
```suggestion
```

here

2021-07-05 17:54 UTC, Jouzo commented on packages/jellyfish-transaction/src/script/expansion.ts
> +
Fixed !

2021-07-05 17:56 UTC, fuxingloh approved these changes

2021-07-06 02:56 UTC, jingyi2811 approved these changes

2021-07-06 02:56 UTC, merged