Siradji/rpc get active masternode count
DeFiCh/jellyfish pull request #648
Opened 2021-09-08 14:10 UTC by siradji

#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:
Added `getActiveMasternodeCount` RPC
#### Which issue(s) does this PR fixes?:

Fixes part of #48

#### Additional comments?:

2021-09-08 14:13 UTC, fuxingloh requested changes

2021-09-08 14:13 UTC, fuxingloh commented on website/docs/jellyfish/api/masternode.md
> +``````
too many `

2021-09-08 14:59 UTC, fuxingloh requested changes

2021-09-09 12:18 UTC, fuxingloh submitted a review, later dismissed

2021-09-09 12:52 UTC, Jouzo commented on packages/jellyfish-api-core/src/category/masternode.ts
> +   * @param {number} [blockCount = 20160] The number of blocks to check for unique masternodes. 20160 is the default.
```suggestion
   * @param {number} [blockCount=20160] The number of blocks to check for unique masternodes.
```

2021-09-09 12:52 UTC, Jouzo approved these changes

2021-09-09 14:24 UTC, fuxingloh approved these changes

2021-09-09 15:16 UTC, Jouzo approved these changes

2021-09-10 04:35 UTC, canonbrother approved these changes

2021-09-10 05:28 UTC, merged