feat(jellyfish-api-core): add isAppliedCustomTransaction RPC
DeFiCh/jellyfish pull request #957
Opened 2022-01-10 01:23 UTC by chanakasameera

What this PR does / why we need it:
Checks that custom transaction was affected on chain

Which issue(s) does this PR fixes?:
Added isAppliedCustomTransaction rpc as part of ongoing #48

2022-01-10 01:51 UTC, chee-chyuan submitted a review, later dismissed
LGTM

2022-01-10 08:09 UTC, surangap commented on packages/jellyfish-api-core/src/category/masternode.ts
> +    return await this.client.call('isappliedcustomtx', [transactionId, blockHeight], 'bignumber')
does not need `bignumber` precision.
```suggestion
    return await this.client.call('isappliedcustomtx', [transactionId, blockHeight], 'number')
```

2022-01-10 08:12 UTC, surangap commented on packages/jellyfish-api-core/__tests__/category/masternode/isAppliedCustomTransaction.test.ts
> +      symbol: 'CUPPER',
Copper?

2022-01-10 08:20 UTC, surangap commented on packages/jellyfish-api-core/__tests__/category/masternode/isAppliedCustomTransaction.test.ts
> +  })
add tests to cover conditionals in https://github.com/DeFiCh/ain/blob/7630137b3ea10269f564f13297f21b997735f38e/src/rpc/util.cpp#L84 for completeness. Also in the test, check for at least a part of the error string.

2022-01-10 08:34 UTC, surangap commented on packages/jellyfish-api-core/__tests__/category/masternode/isAppliedCustomTransaction.test.ts
> +  const container = new MasterNodeRegTestContainer()
try to use `testing.container`, we plan to put the container creation inside `testing` class.
you can find sample code in loan tests.
@chee-chyuan FYI

2022-01-10 08:35 UTC, surangap requested changes
added some comments.

2022-01-10 18:57 UTC, surangap commented on packages/jellyfish-api-core/__tests__/category/masternode/isAppliedCustomTransaction.test.ts
> +  const client = new ContainerAdapterClient(container)
inside testing, you already have a RPC client. can use that

2022-01-10 18:57 UTC, surangap commented on packages/jellyfish-api-core/__tests__/category/masternode/isAppliedCustomTransaction.test.ts
> +    const goldHeight = await client.blockchain.getBlockCount()
```suggestion
    const goldHeight = await testing.rpc.blockchain.getBlockCount()
```

2022-01-12 06:15 UTC, surangap commented on packages/jellyfish-api-core/__tests__/category/masternode/isAppliedCustomTransaction.test.ts
> +  const client = testing.rpc
```suggestion
```

2022-01-12 06:16 UTC, surangap commented on packages/jellyfish-api-core/__tests__/category/masternode/isAppliedCustomTransaction.test.ts
> +    await container.waitForWalletCoinbaseMaturity()
```suggestion
        await testing.container.start()
        await testing.container.waitForWalletCoinbaseMaturity()
```

2022-01-12 06:17 UTC, surangap commented on packages/jellyfish-api-core/__tests__/category/masternode/isAppliedCustomTransaction.test.ts
> +    await container.stop()
```suggestion
    await testing.container.stop()
```

2022-01-12 08:44 UTC, canonbrother submitted a review, later dismissed

2022-02-16 05:04 UTC, surangap approved these changes

2022-02-16 05:54 UTC, canonbrother approved these changes

2022-02-16 09:27 UTC, chee-chyuan approved these changes

2022-02-23 06:53 UTC, fuxingloh approved these changes

2022-02-23 06:53 UTC, merged